version: '3.8'

services:
  backend:
    build:
      context: ./ResourcingApi
    image: resourcing-api
    ports:
      - "5000:80"
    networks:
      - app-network

  frontend:
    build:
      context: ./ResourcingUi
    image: resourcing-ui
    ports:
      - "3000:80"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
