name: .NET Core CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up .NET SDK
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '8.0.403'  # Specify the .NET version you're using
    
    - name: Clear .NET Core cache
      run: dotnet nuget locals all --clear

    - name: Restore dependencies
      run: dotnet restore

    - name: Build the project
      run: dotnet build

    - name: Run xUnit tests
      run: dotnet test ./ResourcingApi.Tests/ResourcingApi.Tests.csproj
