name: .NET Core CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up .NET SDK
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '8.0.x'  # Specify the .NET version you're using

    - name: Restore dependencies
      run: dotnet restore

    - name: Build the project
      run: dotnet build --configuration Release

    - name: Run xUnit tests
      run: dotnet test --configuration Release --no-build --verbosity normal

    - name: Publish test results
      if: always()
      run: |
        # Create the test results directory
        mkdir -p test-results
        # Copy the test results to the directory
        cp -r ./TestResults/. test-results/
